/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.MayTinhDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.MayTinh;
import utils.Utils;

/**
 *
 * @author Admin
 */
public class MayTinhPanel extends javax.swing.JPanel {

    private MayTinhDAO mayTinhDAO;
    /**
     * Creates new form MayTinhPanel
     */
    public MayTinhPanel() {
        initComponents();
        
        cbxXuatXu.removeAllItems();
        cbxXuatXu.addItem("Nhập khẩu");
        cbxXuatXu.addItem("Nội địa");
        cbxXuatXu.addItem("Liên doanh");

        mayTinhDAO = new MayTinhDAO();
        resetAddForm();
        loadTable();
        lblSuccess.setVisible(false);
    }
    
    public void resetAddForm() {
        txtTen.setEnabled(false);
        cbxXuatXu.setEnabled(false);
        txtNamNhap.setEnabled(false);
        txtCauHinh.setEnabled(false);
        
        txtTen.setText("");
        cbxXuatXu.setSelectedIndex(0);
        txtNamNhap.setText("");
        txtCauHinh.setText("");
        
        errTen.setText("");
        errXuatXu.setText("");
        errNamNhap.setText("");
        errCauHinh.setText("");

        btnThem.setEnabled(true);
        btnOk.setEnabled(false);
        btnHuy.setEnabled(false);
    }
    
    public void loadTable() {
        List<MayTinh> dsMayTinh = mayTinhDAO.getAll();
        DefaultTableModel menuItemTableModel = (DefaultTableModel) tblMayTinh.getModel();
        for (int i = menuItemTableModel.getRowCount() - 1; i >= 0; i--) {
            menuItemTableModel.removeRow(i);
        }
        for (MayTinh item : dsMayTinh) {
            Object[] data = new Object[]{
                item.getSoHieu(),
                item.getTen(),
                item.getXuatXu(),
                item.getNamNhap(),
                item.getCauHinh()
            };
            menuItemTableModel.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMayTinh = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNamNhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCauHinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxXuatXu = new javax.swing.JComboBox<>();
        errTen = new javax.swing.JLabel();
        errXuatXu = new javax.swing.JLabel();
        errNamNhap = new javax.swing.JLabel();
        errCauHinh = new javax.swing.JLabel();
        lblSuccess = new javax.swing.JLabel();

        tblMayTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số hiệu", "Tên", "Xuất xứ", "Năm nhập", "Cấu hình"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMayTinh);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Quản lý Máy tính");

        jLabel2.setText("Tên:");

        jLabel3.setText("Xuất xứ:");

        jLabel4.setText("Năm nhập:");

        jLabel5.setText("Cấu hình:");

        cbxXuatXu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        errTen.setForeground(new java.awt.Color(255, 51, 0));
        errTen.setText("jLabel6");

        errXuatXu.setForeground(new java.awt.Color(255, 51, 0));
        errXuatXu.setText("jLabel6");

        errNamNhap.setForeground(new java.awt.Color(255, 51, 0));
        errNamNhap.setText("jLabel6");

        errCauHinh.setForeground(new java.awt.Color(255, 51, 0));
        errCauHinh.setText("jLabel6");

        lblSuccess.setForeground(new java.awt.Color(51, 153, 0));
        lblSuccess.setText("Thêm thành công!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCauHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txtNamNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txtTen)
                            .addComponent(cbxXuatXu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errTen)
                            .addComponent(errXuatXu)
                            .addComponent(errNamNhap)
                            .addComponent(errCauHinh)))
                    .addComponent(lblSuccess))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuy))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(errTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errXuatXu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(errNamNhap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCauHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(errCauHinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSuccess)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtTen.setEnabled(true);
        cbxXuatXu.setEnabled(true);
        txtNamNhap.setEnabled(true);
        txtCauHinh.setEnabled(true);
        
        btnThem.setEnabled(false);
        btnOk.setEnabled(true);
        btnHuy.setEnabled(true);
        
        lblSuccess.setVisible(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        resetAddForm();
        lblSuccess.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String ten = txtTen.getText();
        String xuatXu = (String) cbxXuatXu.getSelectedItem();
        String namNhapStr = txtNamNhap.getText();
        String cauHinh = txtCauHinh.getText();
        
        int namNhap = 0;

        boolean isValid = true;
        errTen.setText("");
        errXuatXu.setText("");
        errNamNhap.setText("");
        errCauHinh.setText("");
        
        if (ten.isEmpty()) {
            isValid = false;
            errTen.setText("Tên không được để trống");
        }
        
        if (namNhapStr.isEmpty()) {
            isValid = false;
            errNamNhap.setText("Năm nhập không được để trống");
        } else if (!Utils.checkIntegerNumberFormat(namNhapStr)) {
            isValid = false;
            errNamNhap.setText("Năm nhập phải là số nguyên dương");
        } else {
            System.out.println(namNhap);
            if (namNhap <= 0) {
                isValid = false;
                errNamNhap.setText("Năm nhập phải là số nguyên dương");
            }
        }
        
        if (cauHinh.isEmpty()) {
            isValid = false;
            errCauHinh.setText("Cấu hình không được để trống");
        }
        
        if (!isValid) {
            return;
        }
        
        MayTinh mayTinh = new MayTinh();
        mayTinh.setTen(ten);
        mayTinh.setXuatXu(xuatXu);
        mayTinh.setNamNhap(namNhap);
        mayTinh.setCauHinh(cauHinh);

        mayTinhDAO.addNew(mayTinh);
        
        loadTable();
        resetAddForm();
        lblSuccess.setVisible(true);
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbxXuatXu;
    private javax.swing.JLabel errCauHinh;
    private javax.swing.JLabel errNamNhap;
    private javax.swing.JLabel errTen;
    private javax.swing.JLabel errXuatXu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JTable tblMayTinh;
    private javax.swing.JTextField txtCauHinh;
    private javax.swing.JTextField txtNamNhap;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
