/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.PhongHocDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.PhongHoc;
import utils.Utils;

/**
 *
 * @author Admin
 */
public class PhongHocPanel extends javax.swing.JPanel {

    private PhongHocDAO phongHocDAO;
    /**
     * Creates new form MayTinhPanel
     */
    public PhongHocPanel() {
        initComponents();

        phongHocDAO = new PhongHocDAO();
        resetAddForm();
        loadTable();
        lblSuccess.setVisible(false);
    }
    
    public void resetAddForm() {
        txtTenPhong.setEnabled(false);
        txtSoMay.setEnabled(false);
        
        txtTenPhong.setText("");
        txtSoMay.setText("");
        
        errTenPhong.setText("");
        errSoMay.setText("");

        btnThem.setEnabled(true);
        btnOk.setEnabled(false);
        btnHuy.setEnabled(false);
    }
    
    public void loadTable() {
        List<PhongHoc> dsPhongHoc = phongHocDAO.getAll();
        DefaultTableModel menuItemTableModel = (DefaultTableModel) tblPhongHoc.getModel();
        for (int i = menuItemTableModel.getRowCount() - 1; i >= 0; i--) {
            menuItemTableModel.removeRow(i);
        }
        for (PhongHoc item : dsPhongHoc) {
            Object[] data = new Object[]{
                item.getMaPhong(),
                item.getTenPhong(),
                item.getSoMay()
            };
            menuItemTableModel.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhongHoc = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoMay = new javax.swing.JTextField();
        errTenPhong = new javax.swing.JLabel();
        errSoMay = new javax.swing.JLabel();
        lblSuccess = new javax.swing.JLabel();

        tblPhongHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phòng", "Tên phòng", "Số máy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPhongHoc);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Quản lý Phòng học");

        jLabel2.setText("Tên phòng:");

        jLabel3.setText("Số máy");

        errTenPhong.setForeground(new java.awt.Color(255, 51, 0));
        errTenPhong.setText("jLabel6");

        errSoMay.setForeground(new java.awt.Color(255, 51, 0));
        errSoMay.setText("jLabel6");

        lblSuccess.setForeground(new java.awt.Color(51, 153, 0));
        lblSuccess.setText("Thêm thành công!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoMay, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txtTenPhong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errTenPhong)
                            .addComponent(errSoMay)))
                    .addComponent(lblSuccess))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuy))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(errTenPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(errSoMay)
                    .addComponent(txtSoMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSuccess)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtTenPhong.setEnabled(true);
        txtSoMay.setEnabled(true);
        
        btnThem.setEnabled(false);
        btnOk.setEnabled(true);
        btnHuy.setEnabled(true);
        
        lblSuccess.setVisible(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        resetAddForm();
        lblSuccess.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String tenPhong = txtTenPhong.getText();
        String soMayStr = txtSoMay.getText();
        
        int soMay = 0;

        boolean isValid = true;
        errTenPhong.setText("");
        errSoMay.setText("");
        
        if (tenPhong.isEmpty()) {
            isValid = false;
            errTenPhong.setText("Tên phòng không được để trống");
        }
        
        if (soMayStr.isEmpty()) {
            isValid = false;
            errSoMay.setText("Số máy không được để trống");
        } else if (!Utils.checkIntegerNumberFormat(soMayStr)) {
            isValid = false;
            errSoMay.setText("Số máy phải là số nguyên dương");
        } else {
            soMay = Integer.parseInt(soMayStr);
            if (soMay <= 0) {
                isValid = false;
                errSoMay.setText("Số máy phải là số nguyên dương");
            }
        }
        
        if (!isValid) {
            return;
        }
        
        PhongHoc phongHoc = new PhongHoc();
        phongHoc.setTenPhong(tenPhong);
        phongHoc.setSoMay(soMay);

        phongHocDAO.addNew(phongHoc);
        
        loadTable();
        resetAddForm();
        lblSuccess.setVisible(true);
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel errSoMay;
    private javax.swing.JLabel errTenPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JTable tblPhongHoc;
    private javax.swing.JTextField txtSoMay;
    private javax.swing.JTextField txtTenPhong;
    // End of variables declaration//GEN-END:variables
}
